### ISSUE TITLE
verbose/quiet option

### ISSUE THREAD

**Issue by falkben** [ExoCTK/exoctk#391] opened 2020-08-04 15:48 UTC
We call `using_gtvt` from exo-mast and it produces a lot of output. We currently handle this on our end by suppressing stdout from this function call, but having a quiet or verbose mode might be nice.

It looks like `get_table` could be another culprit, called by using_gtvt.

**Comment by hover2pi** [comment] 2021-03-16 14:18
Duplicate of #302

**Closed by hover2pi** 2021-03-16 14:18 UTC
Labels: 3: LOW PRIORITY, Category: Optimization, Tool: contam_visibility, Urgent: User Submission
